@apiurl = http://localhost:4000/comments

### get comments
GET {{apiurl}}

### create comment
POST {{apiurl}}
Content-Type: application/json

{
"author": "Tommy D", "comment": "Great great! Suxxess"
}

### get one comment
GET {{apiurl}}/61451cc127e661058d001c3a

### update comment
PUT {{apiurl}}/61451cc127e661058d001c3a
Content-Type: application/json

{
"comment": "Sick API fam'"
}

### delete comment
DELETE {{apiurl}}/61451cc127e661058d001c3a