### GET http://localhost:3000/comments

### POST http://localhost:3000/comments Content-Type: application/json

{
"author": "Thomas Shelby", "comment": "Great"
}

### GET http://localhost:3000/comments/614313b2e2e59136ea454c14

### PUT http://localhost:3000/comments/614313b2e2e59136ea454c14 Content-Type: application/json

{
"comment": "Sick API fam'"
}